name: build
on:
  workflow_dispatch:
  pull_request:
jobs:
  juno:
    name: Build and Scan Juno
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image
        run: |
          docker build -t juno  .

      - name: Juno vulnerability scan
        uses: aquasecurity/trivy-action@0.21.0
        with:
          image-ref: 'juno'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'